[project]
name = "heartless"
version = "0.0.1"
description = "Solució practica 1 sobre ablació de cor"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "notebook>=7.5.0",
    "numpy>=2.3.5",
]
